config/routes.rb
Rails.application.routes.draw do
  root 'authors#index'
  resources :authors do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  accepts_nested_attributes_for :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
    2.times { @author.books.build }
    # @author.books.build
  end

  def create
    @author = Author.create(author_params)
    if @author.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if  @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path
  end

  private
  def author_params
    params.require(:author).permit(:name,:age ,books_attributes: [:id, :name , :price , :quantity])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @author = Author.find(params[:author_id])
    @book = @author.books.create(book_params)
    if @book.save
      redirect_to @author
    else
      redirect_to root_path
    end
  end

  def destroy
    @author = Author.find(params[:author_id])
    @book = @author.books.find(params[:id])
    @book.destroy

    redirect_to @author
  end

  private
  def book_params
    params.require(:book).permit(:name,:price,:quantity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author do |f|%>
    <%= f.label :name , "Name : "%>
    <%= f.text_field :name , placeholder:"Enter author name"%><br><br>

    <%= f.label :age , "Age : "%>
    <%= f.text_field :age , placeholder:"Enter author age"%><br><br>

    <%= f.fields_for :books do |book_form| %>
        <%= book_form.label :name , "Book Name"%>
        <%= book_form.text_field :name , placeholder:"Enter book name" %><br><br>

        <%= book_form.label :quantity %>
        <%= book_form.text_field :quantity , placeholder:"Enter book quntity"%><br><br>

        <%= book_form.label :price %>
        <%= book_form.text_field :price , placeholder:"Enter book price"%><br><br>
    <% end %>

    <%= f.submit "Save Author"%>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author Details</h1>
<%= render "form" %>

app/views/authors/index.html.erb
<h1>Authors List</h1>
<% @authors.each do |author|%>
    Name : <%= link_to author.name , author%><br>
    Age : <%= author.age %><br><br>
<% end %>
<%= link_to "New Author" , new_author_path %>

app/views/authors/new.html.erb
<h1>New Author Register</h1>
<%= render "form" %>

app/views/authors/show.html.erb
<h1> Author Details </h1>
Name : <%= @author.name %><br>
Age : <%= @author.age %><br><br>

<%= link_to "Edit Author" , edit_author_path %><br><br>
<%= link_to "Delete Author" , author_path , data:{
    turbo_method: :delete,
    turbo_confirm:"Are you sure?"
}%><br><br>
<%= link_to "View All" , root_path%>

<h1> Books List </h1>
<% if @author.books.present? %>
    <% @author.books.each do |book|%>
        Book ID : <%= book.id %><br>
        Name : <%= book.name %><br>
        Price : <%= book.price %><br>
        Quantity : <%= book.quantity %><br>
        <%= link_to "Delete Book" , author_book_path(@author,book),data:{
            turbo_method: :delete,
            turbo_confirm:"Are you sure?"
        }%><br><br>
    <% end %>
<% end %>

<h1> New Book </h1>
<%= form_with model: [@author , Book.new] do |f| %>
    <%= f.label :name , "Name : "%>
    <%= f.text_field :name , placeholder:"Enter Book Name"%><br><br>

    <%= f.label :price , "price : "%>
    <%= f.text_field :price , placeholder:"Enter Book price"%><br><br>

    <%= f.label :quantity , "Quantity : "%>
    <%= f.text_field :quantity , placeholder:"Enter Book quantity"%><br><br>
    
    <%= f.submit "Save book"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajaxexp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>